### ISSUE TITLE
cant add

### ISSUE THREAD

**Issue by dmodoomsirius** [LatvianModder/CurseGraph#3]
I can't add http://minecraft.curseforge.com/mc-mods/72153-mad-science or http://minecraft.curseforge.com/mc-mods/227048-voltz-engine

similar to #1 tried voltz-engine and 227048-voltz-engine and it says failed to add.

**Comment by LatvianModder** [comment]
Hmm. It seems like it doesn't have a .json file at all, checked the site, sorry, nothing I can really do here :( Ill let you know, if I find a solition

**Comment by LatvianModder** [comment]
I can now add Mad Science with "mad-science", but adding "227048-voltz-engine" crashes and deletes everything O_O

**Comment by LatvianModder** [comment]
Will be fixed in v1.1.6+
